Create CoreGamePlay
outscal/hitman pull request #3
Opened 2019-02-28 06:43 UTC by SwapnilOutscal

- Added PathSystem
- Added PlayerSystem
- Added InputSystem
- Added EnemySystem (Basic)
- Added Interactable Pickup System (Basic)
- Added 3 Levels

2019-02-28 11:58 UTC, mayankgrover reviewed
why is there a apk file in the repository?

2019-02-28 12:39 UTC, mayankgrover requested changes

2019-02-28 12:39 UTC, mayankgrover commented on hitman-go/Assets/Scripts/Common/NodeData.cs
> +        public int up=-1, down=-1, left=-1, right=-1;
why 4 variables with same value?

2019-02-28 12:39 UTC, mayankgrover commented on hitman-go/Assets/Scripts/Common/NodeData.cs
> +    public enum NodeProperty
separate files

2019-02-28 12:39 UTC, mayankgrover commented on hitman-go/Assets/Scripts/Common/GameplayEnums.cs
> +    public enum Directions
separate files

2019-02-28 12:39 UTC, mayankgrover commented on hitman-go/Assets/Scripts/Enemy/CircularCopEnemyController.cs
> +        public CircularCopEnemyController(IEnemyService _enemyService, IPathService _pathService, IGameService _gameService, Vector3 _spawnLocation, EnemyScriptableObject _enemyScriptableObject, int
too many dependencies - discuss

2019-02-28 12:39 UTC, mayankgrover commented on hitman-go/Assets/Scripts/Enemy/EnemyController.cs
> +            enemyInstance.transform.localPosition = spawnLocation;
anything to do with the view should be inside view script not directly in controller

2019-02-28 12:39 UTC, mayankgrover commented on hitman-go/Assets/Scripts/Common/GameInstaller.cs
> +        Container.BindSignal<StateChangeSignal>().ToMethod<GameService>(x=>x.ChangeState).FromResolve();
why are we binding to the signal here and not subscribing like other services

2019-02-28 12:39 UTC, mayankgrover commented on hitman-go/Assets/Scripts/Enemy/EnemyService.cs
> +            List<int> enemyKey = new List<int>();
why do we need another list?

2019-02-28 12:39 UTC, mayankgrover commented on hitman-go/Assets/Scripts/Enemy/EnemyService.cs
> +        private void SpawnSingleEnemy(EnemyScriptableObject _enemyScriptableObject)
too big needs refactoring asap

2019-02-28 12:39 UTC, mayankgrover commented on hitman-go/Assets/Scripts/Enemy/PatrollingEnemyController.cs
> +            currentEnemyView.GetGameObject().transform.localPosition = pathService.GetNodeLocation(nodeID);
move to view

2019-02-28 12:39 UTC, mayankgrover commented on hitman-go/Assets/Scripts/Enemy/IEnemyController.cs
> +    public interface IEnemyController
why is it empty? no one is calling any function on enemy controlller?

2019-02-28 12:39 UTC, mayankgrover commented on hitman-go/Assets/Scripts/PathSystem/PathService.cs
> +        NodeControllerView nodeprefab, targetNode;
why is service holding view references ?

2019-02-28 12:39 UTC, mayankgrover commented on hitman-go/Assets/Scripts/PathSystem/PathService.cs
> +    public class PathService : IPathService
getting too big - needs refactoring

2019-02-28 12:39 UTC, mayankgrover commented on hitman-go/Assets/Scripts/Player/Interfaces/IPlayerController.cs
> +    public interface IPlayerController
empty why ?

2019-02-28 12:39 UTC, mayankgrover commented on hitman-go/Assets/Scripts/Player/PlayerController.cs
> +        GameObject playerInstance;
controller should not do anything on the player instance. it should only be calling player view functions

2019-02-28 12:39 UTC, mayankgrover commented on hitman-go/Assets/Scripts/Player/PlayerService.cs
> +            _signalBus = signalBus;
inconsistent naming with "_"

2019-02-28 12:39 UTC, mayankgrover commented on hitman-go/Assets/Scripts/Player/PlayerService.cs
> +            _signalBus.TryFire(new StateChangeSignal());
shouldn't we fire game finished signal when the game is over ?

2019-02-28 12:39 UTC, mayankgrover commented on hitman-go/Assets/Scripts/Player/PlayerView.cs
> +        public GameObject GetGameObject()
remove

2019-03-01 04:31 UTC, VinayKashyap15 commented on hitman-go/Assets/Scripts/Player/PlayerService.cs
> +            _signalBus.TryFire(new StateChangeSignal());
there is another game over signal  for that.
 Game finished means that finish condition is met

2019-03-01 04:31 UTC, VinayKashyap15 commented on hitman-go/Assets/Scripts/Player/PlayerView.cs
> +        public GameObject GetGameObject()
okay

2019-03-04 04:44 UTC, VinayKashyap15 commented on hitman-go/Assets/Scripts/Enemy/EnemyService.cs
> +            List<int> enemyKey = new List<int>();
removed it. previously i was using a dictionary. Now i am not

2019-03-04 04:46 UTC, VinayKashyap15 commented on hitman-go/Assets/Scripts/Enemy/PatrollingEnemyController.cs
> +            currentEnemyView.GetGameObject().transform.localPosition = pathService.GetNodeLocation(nodeID);
moved to view

2019-03-04 04:46 UTC, VinayKashyap15 commented on hitman-go/Assets/Scripts/Enemy/IEnemyController.cs
> +    public interface IEnemyController
resolved

2019-03-12 12:41 UTC, mayankgrover approved these changes

2019-03-12 12:41 UTC, mayankgrover commented on hitman-go/Assets/Scripts/3StarSystem/IStarService.cs
> +        void SetTotalEnemyandMaxPlayerMoves(int enemy, int playerMoves);
should be two separate functions SRP violation

2019-03-12 12:41 UTC, mayankgrover commented on hitman-go/Assets/Scripts/3StarSystem/StarSystemService.cs
> +            this.signalBus = signalBus;
not even needed - not used outside the constructor

2019-03-12 12:41 UTC, mayankgrover commented on hitman-go/Assets/Scripts/3StarSystem/StarSystemService.cs
> +    public class StarSystemService : IStarService
naming

2019-03-12 12:41 UTC, mayankgrover commented on hitman-go/Assets/Scripts/Camera/CameraManager.cs
> +    public class CameraManager : ICamera
Manager or Service - be consistent

2019-03-12 12:41 UTC, mayankgrover commented on hitman-go/Assets/Scripts/Camera/CameraScriptable/CameraScriptableObj.cs
> +    public struct CameraData
CameraModel

2019-03-12 12:41 UTC, mayankgrover commented on hitman-go/Assets/Scripts/Common/ScriptableNode.cs
> +        public int up = -1, down = -1, left = -1, right = -1;
why -1

2019-03-12 12:41 UTC, mayankgrover commented on hitman-go/Assets/Scripts/Editor/GraphValidator.cs
> +            hzero = ((int)(Mathf.Ceil(((float)graph.maxwidth / 2)))) - 1; vzero = ((int)(Mathf.Ceil(((float)graph.maxhight / 2))) - 1);
super hard to read

2019-03-12 12:41 UTC, mayankgrover commented on hitman-go/Assets/Scripts/Enemy/Controllers/BiDirectionalGuardEnemyController.cs
> +        public BiDirectionalEnemyController(IEnemyService _enemyService, IPathService _pathService, IGameService _gameService, Vector3 _spawnLocation, EnemyScriptableObject _enemyScriptableObject, in
is this readable?

2019-03-12 12:41 UTC, mayankgrover commented on hitman-go/Assets/Scripts/Enemy/Controllers/CircularCopEnemyController.cs
> +        async public override Task Move()
too big - single function
plus state machine logic

2019-03-12 12:41 UTC, mayankgrover commented on hitman-go/Assets/Scripts/Enemy/Controllers/EnemyController.cs
> +        protected virtual void ChangeDirection()
duplicate logic from Dual facing cop

2019-03-12 12:41 UTC, mayankgrover commented on hitman-go/Assets/Scripts/Enemy/Controllers/EnemyController.cs
> +       public bool IsPlayerKillable()
why is this needed ?

2019-03-12 12:41 UTC, mayankgrover commented on hitman-go/Assets/Scripts/Enemy/Controllers/PatrollingEnemyController.cs
> +            if (nodeID == -1)
no clue what -1 means

2019-03-12 12:41 UTC, mayankgrover commented on hitman-go/Assets/Scripts/Enemy/EnemyFactory.cs
> +            switch (_enemyScriptableObject.enemyType)
too much duplication in each switch

2019-03-12 12:41 UTC, mayankgrover commented on hitman-go/Assets/Scripts/Enemy/EnemyService.cs
> +    public class EnemyService : IEnemyService
250 Loc

2019-03-12 12:41 UTC, mayankgrover commented on hitman-go/Assets/Scripts/Enemy/States/EnemyChaseState.cs
> +    public class EnemyChaseState : IEnemyState
enemy states have no logic - they are just empty class

2019-03-12 12:41 UTC, mayankgrover commented on hitman-go/Assets/Scripts/InputSystem/Interfaces/ITapDetect.cs
> +        GameObject ReturnObject(Vector2 position, LayerMask layerMask);
not a good name

2019-03-12 12:41 UTC, mayankgrover commented on hitman-go/Assets/Scripts/Player/PlayerService.cs
> +        public SignalBus GetSignalBus()
why are these kind of functions needed?

2019-03-14 09:40 UTC, merged